# Generated by Django 3.2.8 on 2021-10-27 10:19

from django.db import migrations, models
import django.utils.timezone
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=posts.models.projectFile),
            preserve_default=False,
        ),
    ]
